//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class Client
    {
        public int Id { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string FirstNames { get; set; }

        [Required(ErrorMessage = "Please select IdentityType")]
        public string IdentityType { get; set; }
        [Required]
        public string IdentityNumber { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfBirth { get; set; }
    }
    
}
